# Generated by Django 2.1 on 2018-08-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_auto_20180815_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
