# Generated by Django 2.1 on 2018-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0005_auto_20180821_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bath',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='bed',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(default='Teshie', max_length=50),
            preserve_default=False,
        ),
    ]
