# Generated by Django 2.1 on 2018-09-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0006_auto_20180825_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='products/2018/08/21/1.jpg', upload_to='products/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
