# Generated by Django 2.1 on 2018-09-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0007_auto_20180902_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bath',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
